global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'identity_provider'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['identity-provider:9000']
        labels:
          application: 'Identity Provider Application'