version: '3.9'

services:

  discovery-server:
    image: "owolny/kierowca-2.0-discovery-server"
    ports:
      - "8761:8761"
    environment:
      - "spring.profiles.active=prod"
    networks:
      - backend

  api-gateway:
    image: "owolny/kierowca-2.0-api-gateway"
    ports:
      - "8080:8080"
    environment:
      - "spring.profiles.active=docker"
      - "EUREKA_SERVER=http://discovery-server:8761"
      - "eureka.instance.prefer-ip-address=true"
    depends_on:
      - discovery-server
    networks:
      - backend

  authorization-server:
    image: "owolny/kierowca-2.0-authorization-server"
    environment:
      - "spring.profiles.active=docker"
      - "eureka.instance.prefer-ip-address=true"
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - backend

networks:
  backend: