version: '3.9'

services:

  discovery-server:
    image: "owolny/apps-discovery-server"
    ports:
      - "8761:8761"
    environment:
      - "spring.profiles.active=prod"
    networks:
      - backend

  api-gateway:
    image: "owolny/apps-api-gateway"
    ports:
      - "8080:8080"
    environment:
      - "spring.profiles.active=docker"
      - "eureka.instance.prefer-ip-address=true"
    depends_on:
      - discovery-server
    networks:
      - backend

  identity-provider:
    image: "owolny/apps-identity-provider"
    ports:
      - "9000:9000"
    environment:
      - "spring.profiles.active=docker"
      - "eureka.instance.prefer-ip-address=true"
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - backend

networks:
  backend: